leftbar:
  brand:
    name: Wang233's Blog
    tagline: 技术分享
    href: /
  menu:
    - id: post
      title: 文章
      icon: default:documents
      url: /
    - id: tags
      title: 标签
      icon: default:hashtag
      url: /tags/
    - id: archives
      title: 归档
      icon: default:calendar
      url: /archives/
    - id: about
      title: 关于
      icon: default:profile
      url: /about/

article:
  listing:
    show_tags: true
  footer:
    license: 转载请注明出处

footer:
  content: © 2026 Wang233  Powered by Hexo & Stellar

inject:
  head_end: '<link rel="stylesheet" href="/css/article-banner-spacing.css">'
  body_end: '<script data-stellar-script="core" src="/js/absolute-dates.js" defer></script>'
