leftbar:
  brand:
    name: Wang233's Blog
    tagline: 技术分享
    href: /
  menu:
    - id: post
      title: 博客
      icon: default:documents
      url: /
    - id: archives
      title: 归档
      icon: default:calendar
      url: /archives/
    - id: about
      title: 关于
      icon: default:profile
      url: /about/
